//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public enum DroneState
{
	Default = 0,
	Following = 1,
	Attacking = 2,
	Avoiding = 3,
	Flirting = 4,
	NumStates = 5
}



