//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

//Class that computes Unity coordinates of an orthographic camera's boundaries
public class OrthographicCameraBoundary
{
	#region Variables
	private float left, right, top, bottom, width, height;
	#endregion

	#region Properties
	public float Left {
		get {
			return this.left;
		}
	}

	public float Right {
		get {
			return this.right;
		}
	}

	public float Top {
		get {
			return this.top;
		}
	}

	public float Bottom {
		get {
			return this.bottom;
		}
	}

	public float Width {
		get {
			return this.width;
		}
	}

	public float Height {
		get {
			return this.height;
		}
	}
	#endregion

	#region Public methods
	public OrthographicCameraBoundary(Camera camera)
	{
		left = -camera.aspect * camera.orthographicSize + camera.transform.position.x;
		right = camera.aspect * camera.orthographicSize + camera.transform.position.x;
		top = camera.orthographicSize + camera.transform.position.y;
		bottom = -camera.orthographicSize + camera.transform.position.y;
		width = right - left;
		height = top - bottom;
	}
	#endregion
}
	

